name: 'Workflow Broker'
description: 'Toolkit for waiting for workflows'
inputs:
  broker_url:
    description: 'broker url'
    required: true
  workflow_id:
    description: 'workflow id'
    required: true
  job_status:
    description: 'Job status'
  report:
    description: 'Force report certain stage'
    required: false
  wait:
    description: 'Wait instead'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
